### ISSUE TITLE
请问是否支持发送本地图片或者base64?是否支持捕获机器人本身的消息?

### ISSUE THREAD

**Issue by jiluowuyan** [go-cqhttp/java#11]
目前个人使用`MessageChain.image()` 过程中,只能发送.image缓存文件.
我尝试过使用`new ImageMessage()` 后`setUrl("本地文件地址")` 进行发送,go-cqhhtp服务端显示 **消息图片上传失败: image type error:** .
是否是我使用了错误的发图方式?我应该如何解决这个问题?
另外我在go-cqhttp里配置了report-self-message: true ,也就是上报机器人自身的消息,但是在使用过程中发现并没有捕获到机器人的发言,我需要加上什么另外的配置吗?

**Comment by xiaoxu97** [comment]
首先，本地文件地址你要确保你的go-cqhttp能通过该路径访问到对应的图片文件，另外image可以发送网络图片的url形式，上报机器人自身消息这个问题，你需要去go-cqhttp中寻找答案。

**Comment by xiaoxu97** [comment]
目前文档并不全面，会在将来慢慢完善文档

**Comment by jiluowuyan** [comment]
本地图片那个我研究了一下,是要符合onebot发送文件规范就行(本地文件应该是`file:///` 开头加上文件地址,base64 则是 `base64://` 加上图片base64内容即可).
然后因为bot的消息类型(post_type)不属于message而是message_sent,导致消息在GroupMessageEvent.isSupport()方法里被过滤掉了.

**Comment by xiaoxu97** [comment]
抱歉我没有看到你说的message_sent,我的意思是,你只需要满足go-cqhttp能访问到你的那个文件就可以,文件形式不重要,如果你go-cqhttp和java程序部署在一起,那么可以直接通过java来处理文件,给到go-cqhttp一个路径,或者可以上传至oss类的文件储存中以url形式发送图片
