### ISSUE TITLE
Token authentication failed!

### ISSUE THREAD

**Issue by is-idea** [go-cqhttp/java#18]
![image](https://user-images.githubusercontent.com/33053444/156096051-85281d04-78f4-437f-9b14-3acfa06f532e.png)
![image](https://user-images.githubusercontent.com/33053444/156096085-c1c32b13-86c7-4eb9-b035-8896b31b9ad7.png)

配置了token为什么还是错误呢?

**Comment by xiaoxu97** [comment]
详细检查一下配置文件，默认情况下5800应该不是正向ws地址，另附一下错误信息截图

**Comment by is-idea** [comment]
> 详细检查一下配置文件，默认情况下5800应该不是正向ws地址，另附一下错误信息截图

5800是我吧配置文件里的5700改了.

**Comment by xiaoxu97** [comment]
5700默认为http方式，目前仅支持正向ws方式，需填写正向ws的端口

**Comment by is-idea** [comment]
> 5700默认为http方式，目前仅支持正向ws方式，需填写正向ws的端口

感谢大佬,我已经连接上了.
但是项目启动后会直接抛出一些异常.
我不太明白问题出在了那里.
![image](https://user-images.githubusercontent.com/33053444/156097509-459774c3-94e6-424b-af7c-6a071a6341d1.png)

**Comment by xiaoxu97** [comment]
使用前应仔细查看一下文档，文档中有说需要更改go-cqhttp的上报格式为Array，后续会更新自动判断上报格式的功能。

**Comment by is-idea** [comment]
> 使用前应仔细查看一下文档，文档中有说需要更改go-cqhttp的上报格式为Array，后续会更新自动判断上报格式的功能。

看到了...十分抱歉,我的低级错误.第一次接触这块东西,不太了解,好人一生平安.感谢您!
