### ISSUE TITLE
java: 找不到符号

### ISSUE THREAD

**Issue by linuxxx** [go-cqhttp/java#21]
@RequiredArgsConstructor(onConstructor = @__(@Autowired))

报错：
java: 找不到符号
  符号: 类 __

**Comment by xiaoxu97** [comment]
没有看懂你这是什么问题:D

**Comment by linuxxx** [comment]
添加好maven依赖和lombok 插件后，idea 编译报错。 提示找不到符号。

**Comment by xiaoxu97** [comment]
你这个问题完全看不出来是哪个类, 提问前请先了解下java基础哦亲:D

**Comment by linuxxx** [comment]
> 

没开汉化插件- -

**Comment by xiaoxu97** [comment]
先对照下文档看看是否漏掉哪一步了，目前猜测可能是lombok依赖没有引用成功

**Comment by linuxxx** [comment]
> 

亲，java基础有的，这个编译不过，而且google找不到问题。这个好多类上面都有这个lombok注解鸭https://github.com/go-cqhttp/java/search?q=%40RequiredArgsConstructor%28。
环境：macbook pro m1 
idea版本：IntelliJ IDEA 2021.3.3 (Community Edition
lombot版本：bundled 213.7172.25

**Comment by linuxxx** [comment]
> > 
> 
> 亲，java基础有的，这个编译不过，而且baidu，google 找遍了找不到问题。这个好多类上面都有这个lombok注解鸭[https://github.com/go-cqhttp/java/search?q=%40RequiredArgsConstructor%28。](https://github.com/go-cqhttp/java/search?q=%40RequiredArgsConstructor%28%E3%80%82) 环境：macbook pro m1 idea版本：IntelliJ IDEA 2021.3.3 (Community Edition lombot版本：bundled 213.7172.25

无法解决也没关系了，已经放弃使用这个库了。

**Comment by xiaoxu97** [comment]
首先，无法解决是因为lombok作者不是我，这个问题你可以查询lombok官方文档中的onX部分，利用的是一个根本不存在的类，另外你提问的时候不贴代码，我目前的能力还不足以支撑我不看代码就能解决问题的地步:D
