### ISSUE TITLE
请问一下，怎么用啊！

### ISSUE THREAD

**Issue by wuxianggujun** [go-cqhttp/java#27]
![image](https://user-images.githubusercontent.com/39469560/208142001-a1fea570-d34f-41f5-8991-92db3465f9c0.png)
我配置了扫描包路劲，导入了implementation 'com.zhuangxv:bot-core:1.0.0'。
使用了@EnableBot注解。
但是不知道怎么接收消息什么的

**Comment by xiaoxu97** [comment]
看文档，接收消息新建一个类并注册bean，然后加上注解即可

**Comment by wuxianggujun** [comment]
> 看文档，接收消息新建一个类并注册bean，然后加上注解即可

可以关闭了，我已经会了。感谢啊
