### ISSUE TITLE
文旦里面的@FriendMessageHander错了

### ISSUE THREAD

**Issue by wuxianggujun** [go-cqhttp/java#28]
![image](https://user-images.githubusercontent.com/39469560/208248303-de16db42-cd6d-4c0f-97ae-88f6d2e7fdd4.png)

**Comment by wuxianggujun** [comment]
![image](https://user-images.githubusercontent.com/39469560/208248350-053c3293-dd06-4620-ac25-6c550de55348.png)

**Comment by xiaoxu97** [comment]
已修复
