### ISSUE TITLE
为什么消息没有被调用

### ISSUE THREAD

**Issue by wuxianggujun** [go-cqhttp/java#29]
![image](https://user-images.githubusercontent.com/39469560/208282682-a860cd37-0bb1-4ce2-881b-aa58f35ec20b.png)
我使用了这些注解，但是没效果

**Comment by xiaoxu97** [comment]
配置文件和go-cqhttp配置正确么

**Comment by wuxianggujun** [comment]
> 配置文件和go-cqhttp配置正确么

正确啊，设置为array。
运行就是事件处理器初始化完成。
但是方法什么的没有注入。

**Comment by xiaoxu97** [comment]
你都没提示连接成功  肯定配置不对

**Comment by wuxianggujun** [comment]
> 

那给你看看我的配置


# go-cqhttp 默认配置文件

account: # 账号相关
  uin:  # QQ账号
  password: '' # 密码为空时使用扫码登录
  encrypt: false  # 是否开启密码加密
  status: 0      # 在线状态 请参考 https://docs.go-cqhttp.org/guide/config.html#在线状态
  relogin: # 重连设置
    delay: 3   # 首次重连延迟, 单位秒
    interval: 3   # 重连间隔
    max-times: 0  # 最大重连次数, 0为无限制

  # 是否使用服务器下发的新地址进行重连
  # 注意, 此设置可能导致在海外服务器上连接情况更差
  use-sso-address: true
  # 是否允许发送临时会话消息
  allow-temp-session: false

heartbeat:
  # 心跳频率, 单位秒
  # -1 为关闭心跳
  interval: 5

message:
  # 上报数据类型
  # 可选: string,array
  post-format: array
  # 是否忽略无效的CQ码, 如果为假将原样发送
  ignore-invalid-cqcode: false
  # 是否强制分片发送消息
  # 分片发送将会带来更快的速度
  # 但是兼容性会有些问题
  force-fragment: false
  # 是否将url分片发送
  fix-url: false
  # 下载图片等请求网络代理
  proxy-rewrite: ''
  # 是否上报自身消息
  report-self-message: false
  # 移除服务端的Reply附带的At
  remove-reply-at: false
  # 为Reply附加更多信息
  extra-reply-data: false
  # 跳过 Mime 扫描, 忽略错误数据
  skip-mime-scan: false

output:
  # 日志等级 trace,debug,info,warn,error
  log-level: warn
  # 日志时效 单位天. 超过这个时间之前的日志将会被自动删除. 设置为 0 表示永久保留.
  log-aging: 15
  # 是否在每次启动时强制创建全新的文件储存日志. 为 false 的情况下将会在上次启动时创建的日志文件续写
  log-force-new: true
  # 是否启用日志颜色
  log-colorful: true
  # 是否启用 DEBUG
  debug: false # 开启调试模式

# 默认中间件锚点
default-middlewares: &default
  # 访问密钥, 强烈推荐在公网的服务器设置
  access-token: ''
  # 事件过滤器文件目录
  filter: ''
  # API限速设置
  # 该设置为全局生效
  # 原 cqhttp 虽然启用了 rate_limit 后缀, 但是基本没插件适配
  # 目前该限速设置为令牌桶算法, 请参考:
  # https://baike.baidu.com/item/%E4%BB%A4%E7%89%8C%E6%A1%B6%E7%AE%97%E6%B3%95/6597000?fr=aladdin
  rate-limit:
    enabled: false # 是否启用限速
    frequency: 1  # 令牌回复频率, 单位秒
    bucket: 1     # 令牌桶大小

database: # 数据库相关设置
  leveldb:
    # 是否启用内置leveldb数据库
    # 启用将会增加10-20MB的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: true

  # 媒体文件缓存， 删除此项则使用缓存文件(旧版行为)
  cache:
    image: data/image.db
    video: data/video.db

# 连接服务列表
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器

  # - http: # HTTP 通信设置
  #     address: 127.0.0.1:5700 # HTTP监听地址
  #     timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
  #     long-polling:   # 长轮询拓展
  #       enabled: false       # 是否开启
  #       max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
  #     middlewares:
  #       <<: *default # 引用默认中间件
  #     post:           # 反向HTTP POST地址列表
  #     #- url: ''                # 地址
  #     #  secret: ''             # 密钥
  #     #  max-retries: 3         # 最大重试，0 时禁用
  #     #  retries-interval: 1500 # 重试时间，单位毫秒，0 时立即
  #     #- url: http://127.0.0.1:5701/ # 地址
  #     #  secret: ''                  # 密钥
  #     #  max-retries: 10             # 最大重试，0 时禁用
  #     #  retries-interval: 1000      # 重试时间，单位毫秒，0 时立即
  # 正向WS设置
  - ws:
      # 正向WS服务器监听地址
      address: 0.0.0.0:8001
      middlewares:
        <<: *default # 引用默认中间件
  # 反向WS设置
  # - ws-reverse:
  #     # 反向WS Universal 地址
  #     # 注意 设置了此项地址后下面两项将会被忽略
  #     universal: ws://robot.wuxianggujun.com
  #     # 反向WS API 地址
  #     api: ws://your_websocket_api.server
  #     # 反向WS Event 地址
  #     event: ws://your_websocket_event.server
  #     # 重连间隔 单位毫秒
  #     reconnect-interval: 3000
  #     middlewares:
  #       <<: *default # 引用默认中间件

**Comment by wuxianggujun** [comment]
![image](https://user-images.githubusercontent.com/39469560/208285621-1ab7d465-b54f-4066-a2d4-88af85990944.png)
![image](https://user-images.githubusercontent.com/39469560/208285633-dedf135c-760d-4bdd-91d4-ad36b46932f4.png)
![image](https://user-images.githubusercontent.com/39469560/208285645-595fc27c-b167-42cf-9872-e7fcd57640a1.png)

**Comment by wuxianggujun** [comment]
![image](https://user-images.githubusercontent.com/39469560/208285694-9f8285e9-c42a-45e4-8dcd-d28147d9e624.png)
springboot的配置文件

**Comment by wuxianggujun** [comment]
> 你都没提示连接成功 肯定配置不对

你可以看看我的配置，哪里错了吗

**Comment by xiaoxu97** [comment]
配置没问题，你有配置防火墙一类的么，如果没有提示连接成功，就说明连接出错了

**Comment by wuxianggujun** [comment]
> 配置没问题，你有配置防火墙一类的么，如果没有提示连接成功，就说明连接出错了

我的服务器防火墙全开放

**Comment by wuxianggujun** [comment]
> 配置没问题，你有配置防火墙一类的么，如果没有提示连接成功，就说明连接出错了

自己写过机器人都是可以的

**Comment by wuxianggujun** [comment]
就这个框架搞不懂，不知道哪里有问题。我看了使用这个框架的开源项目，也没有什么配置

**Comment by xiaoxu97** [comment]
建议你加一下Accesstoken后再试一下

**Comment by wuxianggujun** [comment]
> 建议你加一下Accesstoken后再试一下

这个是自定义的吗

**Comment by xiaoxu97** [comment]
go-cqhttp里面配置，机器人端也要配置

**Comment by wuxianggujun** [comment]
> go-cqhttp里面配置，机器人端也要配置

我试试

**Comment by wuxianggujun** [comment]
> go-cqhttp里面配置，机器人端也要配置

![image](https://user-images.githubusercontent.com/39469560/208285945-29f88484-435b-44cb-8229-bafa6915f617.png)
服务器配置好了
![image](https://user-images.githubusercontent.com/39469560/208285963-f574baeb-8382-405e-9a30-64d401f4145c.png)
ji机器人还是这样子

**Comment by xiaoxu97** [comment]
这样就可以了呀，收到消息没有进入事件处理器么？

**Comment by xiaoxu97** [comment]
你可以查看一下你的类有没有注册bean

**Comment by wuxianggujun** [comment]
![image](https://user-images.githubusercontent.com/39469560/208286159-be0e8b68-7b16-4fb6-9e7f-40d0c7a95f57.png)
应该注册了
![image](https://user-images.githubusercontent.com/39469560/208286176-b486ca65-33a3-4f1c-b470-2dfb5c53aecd.png)

**Comment by wuxianggujun** [comment]
> 这样就可以了呀，收到消息没有进入事件处理器么？

对啊

**Comment by xiaoxu97** [comment]
方便的话可以加我qq远程帮你看一下632008666

**Comment by wuxianggujun** [comment]
![image](https://user-images.githubusercontent.com/39469560/208286321-3a39eb14-5052-4e7c-a32c-2a8938b4b591.png)
![image](https://user-images.githubusercontent.com/39469560/208286329-287ac620-5818-4149-a8af-4f1a7ee11bde.png)
给项目加了日志

**Comment by wuxianggujun** [comment]
进不去

**Comment by wuxianggujun** [comment]
> 632008666

同意一下

**Comment by thinkingme** [comment]
我也遇到同样问题了，咋解决的

**Comment by thinkingme** [comment]
wshandler可以捕捉到，但是没进判断里面

![image](https://user-images.githubusercontent.com/54928012/208603475-103dffe1-ad42-4d85-8b74-99e0dace2836.png)

**Comment by xiaoxu97** [comment]
e9473890e03ac28ec06ca84e7aeb25deb7cdb640
