### ISSUE TITLE
Bot如何主动发送消息

### ISSUE THREAD

**Issue by reine-ishyanami** [go-cqhttp/java#31]
是否提供了一个给Bot对象主动发送消息的方法？看readme没懂

**Comment by xiaoxu97** [comment]
可以使用BotFactory.getBot来获取bot对象，目前readme还不完善，抽空会补全。

**Comment by reine-ishyanami** [comment]
> 可以使用BotFactory.getBot来获取bot对象，目前readme还不完善，抽空会补全。

如何在与go-cqhttp建立连接后，注入一个全局Bot的Bean对象，以供后续其他组件使用

**Comment by xiaoxu97** [comment]
> > 可以使用BotFactory.getBot来获取bot对象，目前readme还不完善，抽空会补全。
> 
> 如何在与go-cqhttp建立连接后，注入一个全局Bot的Bean对象，以供后续其他组件使用

不建议自行维护bot对象，BotFactory就是全局的获取bot对象列表，包含已经建立连接的所有对象，当然如果你依然想自行维护，可以实现BotContext接口，并将这个类注册bean(@Component注解即可)，当bot连接成功后，会调用BotContext的connected方法
