### ISSUE TITLE
无法的找到标记@GroupUserAddHandler

### ISSUE THREAD

**Issue by lxzcl** [go-cqhttp/java#32]
![image](https://user-images.githubusercontent.com/41499707/230045920-13f4a019-995a-45c5-8f01-1d07fda4d3c7.png)

pom配置为
![image](https://user-images.githubusercontent.com/41499707/230046200-005cd634-233c-4b3d-88cf-a0145fefb111.png)
在annotation文件夹内页没找到
GroupUserAddHandler 
![image](https://user-images.githubusercontent.com/41499707/230046970-d4f60ee9-5e4c-4815-a1c5-27a32ad3191e.png)

**Comment by xiaoxu97** [comment]
@MemberAddHandler
