### ISSUE TITLE
Go-cqhttp failed to connect, Token authentication failed!

### ISSUE THREAD

**Issue by OHOdoinb** [go-cqhttp/java#7]
这个access_token默认不是为空吗？也改过access_token，就是连不上。

**Comment by xiaoxu97** [comment]
要保证access_token与miraigo中一致且不能为空

**Comment by OHOdoinb** [comment]
![image](https://user-images.githubusercontent.com/49581853/115945539-d6550580-a4ee-11eb-9143-de275cf982b1.png)
![image](https://user-images.githubusercontent.com/49581853/115945543-d94ff600-a4ee-11eb-912a-f00478e3c4e0.png)
不是两个保持一致吗？改了不为空也是这个错。

**Comment by xiaoxu97** [comment]
可以看一下你是如何改的么

**Comment by OHOdoinb** [comment]
![image](https://user-images.githubusercontent.com/49581853/115946089-7875ed00-a4f1-11eb-97e2-29a5de67bd99.png)

**Comment by xiaoxu97** [comment]
你可以在WebSocketHandler类的38行打一个断点，来看一下读取的配置信息。

**Comment by OHOdoinb** [comment]
![image](https://user-images.githubusercontent.com/49581853/115946515-4ade7300-a4f4-11eb-91ad-a6e50a7d51e4.png)

**Comment by xiaoxu97** [comment]
你连错了，本项目是使用websocket链接，如果你没有修改，5700端口是http通信端口，请改成6700端口

**Comment by OHOdoinb** [comment]
![image](https://user-images.githubusercontent.com/49581853/115947034-a3633f80-a4f7-11eb-86f8-cc9f5b91f5cc.png)

**Comment by xiaoxu97** [comment]
检查一下go-cqhttp的配置是否开启websocket上报

**Comment by OHOdoinb** [comment]
![image](https://user-images.githubusercontent.com/49581853/115947835-07d4cd80-a4fd-11eb-8a19-0cfb4df6bd03.png)

**Comment by xiaoxu97** [comment]
ws api
