### ISSUE TITLE
[Feature Request]能否支持wss协议以及自定义path

### ISSUE THREAD

**Issue by kzw200015** [go-cqhttp/java#9]
我的cqhttp部署在反向代理后，建议支持自定义URL，提供更高的自由度，类似`wss://example.com:443/ws`这样的格式

**Comment by xiaoxu97** [comment]
> 我的cqhttp部署在反向代理后，建议支持自定义URL，提供更高的自由度，类似`wss://example.com:443/ws`这样的格式

已经支持 [bae3ffd](https://github.com/go-cqhttp/java/commit/bae3ffd6ed04ea26a638c06cb2aeb6cdbcdea1dd)
